// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Proyecto_Web_MVC_1P_Grupo_2_5544_.Migrations
{
    [DbContext(typeof(DBSsqlProyectoMVC_Grupo2))]
    [Migration("20250430122819_Migracion Inicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_Web_MVC_1P_Grupo_2_5544_.Models.Cliente", b =>
                {
                    b.Property<int>("clienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("clienteId"));

                    b.Property<string>("correoCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nombreCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("telefonoCliente")
                        .HasColumnType("int");

                    b.HasKey("clienteId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Proyecto_Web_MVC_1P_Grupo_2_5544_.Models.Espacios", b =>
                {
                    b.Property<int>("espacioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("espacioId"));

                    b.Property<bool>("estadoEspacio")
                        .HasColumnType("bit");

                    b.Property<int?>("vehiculoId")
                        .HasColumnType("int");

                    b.HasKey("espacioId");

                    b.HasIndex("vehiculoId");

                    b.ToTable("Espacios");
                });

            modelBuilder.Entity("Proyecto_Web_MVC_1P_Grupo_2_5544_.Models.Pago", b =>
                {
                    b.Property<int>("pagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pagoId"));

                    b.Property<int>("clienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaPago")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("montoPagado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("vehiculoId")
                        .HasColumnType("int");

                    b.HasKey("pagoId");

                    b.HasIndex("clienteId");

                    b.HasIndex("vehiculoId");

                    b.ToTable("Pago");
                });

            modelBuilder.Entity("Proyecto_Web_MVC_1P_Grupo_2_5544_.Models.Registros", b =>
                {
                    b.Property<int>("registroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("registroId"));

                    b.Property<int>("clienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("pagoRealizado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("vehiculoId")
                        .HasColumnType("int");

                    b.HasKey("registroId");

                    b.HasIndex("clienteId");

                    b.HasIndex("vehiculoId");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("Proyecto_Web_MVC_1P_Grupo_2_5544_.Models.Vehiculo", b =>
                {
                    b.Property<int>("vehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("vehiculoId"));

                    b.Property<int>("clienteId")
                        .HasColumnType("int");

                    b.Property<string>("colorVehiculo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("fechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<string>("marcaVehiculo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("modeloVehiculo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("placaVehiculo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("vehiculoId");

                    b.HasIndex("clienteId");

                    b.ToTable("Vehiculo");
                });

            modelBuilder.Entity("Proyecto_Web_MVC_1P_Grupo_2_5544_.Models.Espacios", b =>
                {
                    b.HasOne("Proyecto_Web_MVC_1P_Grupo_2_5544_.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("vehiculoId");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Proyecto_Web_MVC_1P_Grupo_2_5544_.Models.Pago", b =>
                {
                    b.HasOne("Proyecto_Web_MVC_1P_Grupo_2_5544_.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("clienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_Web_MVC_1P_Grupo_2_5544_.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("vehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Proyecto_Web_MVC_1P_Grupo_2_5544_.Models.Registros", b =>
                {
                    b.HasOne("Proyecto_Web_MVC_1P_Grupo_2_5544_.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("clienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_Web_MVC_1P_Grupo_2_5544_.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("vehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Proyecto_Web_MVC_1P_Grupo_2_5544_.Models.Vehiculo", b =>
                {
                    b.HasOne("Proyecto_Web_MVC_1P_Grupo_2_5544_.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("clienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
